Project.create(name: "Ukraine Lumber", image_url: "/images/firtree.jpg", materials: "Fir wood from Northwestern China", instructions:"Pulp, renew, and reassemble wood.", user_id: 1)
Project.create(name: "Mexican Sobrero", image_url: "/images/sombrero.jpg", materials: "Clean yard hay + paint", instructions:"Weave in circles with colored tree bark.", user_id: 2)
Project.create(name: "Metal Armour", image_url: "/images/220px-italian.jpg", materials: "Finished steel and oil for shine.", instructions:"Must have Welding experience.", user_id: 3)
Project.create(name: "Reusable Paper", image_url: "/images/paper.jpg", materials: "Air-based elements", instructions:"Training required.", user_id: 4)
Project.create(name: "Magazine Printer", image_url: "/images/ink.jpg", materials: "Liquid gel from fermented soil for ink.", instructions:"Apply to Harmonious Living School", user_id: 5)
Project.create(name: "Miny Toy Box", image_url: "/images/toybox.jpg", materials: "Old wood from used furniture.", instructions:"Come join our classes weekly in Santa Monica.", user_id: 6)
Project.create(name: "Sensitivity Training Kit", image_url: "/images/qi.jpg", materials: "Qi-based lifestyle, excluding heavy energy comsumption.", instructions:"Apply to Harmonious Living School", user_id: 7)
Project.create(name: "Lipchap from Beeswax", image_url: "/images/lipchap.jpg", materials: "Made from natural bees freely roaming Upper Continent.", instructions:"Live and work at the resthouse in forested land near Tobago.", user_id: 8)
Project.create(name: "Healthy Food Alternative", image_url: "/images/woodsy.jpg", materials: "Gathered material that is in tune with the needs of our times.", instructions:"Use food from resources that are often ignored.", user_id: 9)
Project.create(name: "Green Vegetation Growth", image_url: "/images/GREENLEAFYVEGETABLES.jpg", materials: "Non technological equipment.", instructions:"Live at Harmonious Living School for one year.", user_id: 10)



User.create(username: "Lalo", email: "lalo@email.com", password: "password")
User.create(username: "Eduoardo Guarez", email: "EdG@email.com", password: "password")
User.create(username: "Ahmed Patel", email: "shinyness@email.com", password: "password")
User.create(username: "Christina", email: "ctina@email.com", password: "password")
User.create(username: "Bagalo", email: "baga@email.com", password: "password")
User.create(username: "Chi Pio", email: "piklo@email.com", password: "password")
User.create(username: "Mega", email: "Eros@email.com", password: "password")
User.create(username: "Kero", email: "kero@email.com", password: "password")
User.create(username: "Jasmine", email: "mine@email.com", password: "password")
User.create(username: "poison", email: "poison@email.com", password: "password")
